kube-controller-manager-arg: 
  - "bind-address=0.0.0.0"
kube-proxy-arg: 
  - "metrics-bind-address=0.0.0.0"
kube-scheduler-arg: 
  - "bind-address=0.0.0.0"
write-kubeconfig-mode: 644
disable-network-policy: true
service-node-port-range: "1-65000"
disable:
  - "traefik"
